### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by k1n3t1c** [pnobbe/flarum-ext-oauth-discord#2]
On `beta.6` could you please update?

```  Problem 1
    - Can only install one of: flarum/core[v0.1.0-beta.5, v0.1.0-beta.6].
    - Can only install one of: flarum/core[v0.1.0-beta.6, v0.1.0-beta.5].
    - Can only install one of: flarum/core[v0.1.0-beta.5, v0.1.0-beta.6].
    - pnobbe/flarum-ext-oauth-discord v1.0 requires flarum/core v0.1.0-beta.5 -> satisfiable by flarum/core[v0.1.0-beta.5].
    - Installation request for pnobbe/flarum-ext-oauth-discord ^1.0 -> satisfiable by pnobbe/flarum-ext-oauth-discord[v1.0].
    - Installation request for flarum/core (locked at v0.1.0-beta.6, required as ^0.1.0) -> satisfiable by flarum/core[v0.1.0-beta.6].
```

**Comment by pnobbe** [comment]
Try updating to the latest version. I hope it worked, but I wasn't able to test it. I don't have a Flarum environment set up right now.

**Comment by k1n3t1c** [comment]
![image](https://cloud.githubusercontent.com/assets/20934051/20357667/cf59ab96-abf6-11e6-8d38-ca9e1f87d286.png)

Hmm, do I have to change the specific version from `^1.0` to `?`.

**Comment by pnobbe** [comment]
Try installing it with 

`composer require pnobbe/flarum-ext-oauth-discord ^v1.0.1beta6`

**Comment by k1n3t1c** [comment]
Thank you so much @pnobbe ! You are the man! 💯

**Comment by pnobbe** [comment]
Glad to hear it's working again.
